### ISSUE TITLE
can't init SSDPDiscovery

### ISSUE THREAD

**Issue by GINNOV** [pierrickrouxel/SSDPClient#1]
I am getting a "initializer is inaccessible due to internal protection level" when I try to use the same code that you have in the tests (Swift4). What am I missing?

**Comment by cristianomatte** [comment]
I've made a [pull request](https://github.com/pierrickrouxel/SSDPClient/pull/2) that updates the `swift-tools-version` to `4.0` and the project to Swift 4.

**Comment by cristianomatte** [comment]
This project has no support for Swift 4 yet. I've already submitted a [pull request](https://github.com/pierrickrouxel/SSDPClient/pull/2) that solves this issue, but it hasn't been reviewed yet.

For now, you can use my [clone](https://github.com/cristianomatte/SSDPClient) from this repository at version `0.2.0`, which is updated to Swift 4.

**Comment by GINNOV** [comment]
much appreciated.
