### ISSUE TITLE
Package could not be resolved in Xcode 12.5

### ISSUE THREAD

**Issue by Dan1973KS** [pierrickrouxel/SSDPClient#10]
The Package could not be resolved in SPM of current Xcode 12.5 (until 12.4 it works!):

"the Swift tools version specification is missing a label; consider inserting 'swift-tools-version:' between the comment marker and the version specifier"

Until my project is relying on your nice helper client, I would like to ask if you can fix this or if you can give me advice on how to fix it myself?

Thanks in advance,
Dan

**Comment by kjpolaszek** [comment]
https://github.com/Playbook-Technologies/SSDPClient/settings/access

**Comment by kjpolaszek** [comment]
It seems like nobody working on it.

https://github.com/Playbook-Technologies/SSDPClient.git

I fixed in on my fork.

**Comment by Dan1973KS** [comment]
Hey!
Thank you so much for the fast response and quick fix - it works like a charm!!

**Comment by pierrickrouxel** [comment]
@kjpolaszek 
I don’t work on it actually but if you want to submit a PR I will integrate it.
