### ISSUE TITLE
No route to host

### ISSUE THREAD

**Issue by SodaSurfer** [pierrickrouxel/SSDPClient#12]
Hi there

when using the library and running it on my macOS (m1) simulator (iOS 14.1) it runs ok and finds the services on my network.
but when running It on a real device, iPhone 8 iOS version 14.6, I always get a socket error:  **No route to host**

any idea why and how to solve it? thanks

**Comment by mayqiyue** [comment]
The same;

**Comment by brandoncordell** [comment]
For anyone else that's run into this you need to request entitlement from Apple to use this in your app for iOS 14+.

https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_networking_multicast
