### ISSUE TITLE
Not working after IOS 16.0 Update

### ISSUE THREAD

**Issue by piyush2greedy** [pierrickrouxel/SSDPClient#13]
Below are the logs

**Started**

[2022-09-17T15:26:27.279+05:30] [ERROR] [SSDPDiscovery.swift:132 discoverService(forDuration:searchTarget:port:)] Socket error: Error code: -9980(0x-26FC), No route to host
Error code: -9980(0x-26FC), No route to host
[2022-09-17T15:26:27.279+05:30] [ERROR] [SSDPDiscovery.swift:75 readResponses()] Socket error: Error code: -9982(0x-26FE), Bad file descriptor
Error code: -9982(0x-26FE), Bad file descriptor

Production is down due to this:

Added on Apple Thread:
https://developer.apple.com/forums/thread/715002

Can u please help:
@pierrickrouxel @kjpolaszek @cristianomatte @okankocyigit

**Comment by LePips** [comment]
This isn't a bug and it's self-explanatory why it doesn't work, the multicast entitlement is now required.

- https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_networking_multicast

**Comment by thejohnlima** [comment]
That's true.

I was facing the same issue, and to get it fixed, I requested the Apple permission by filling this:
https://developer.apple.com/contact/request/networking-multicast

After get the approve, go to **Certificates, Identifiers & Profiles** on developer portal, Additional Capabilities and mark the 	
`Multicast Networking` checkbox.

On Xcode, add this to your entitlement file:
```xml
<key>com.apple.developer.networking.multicast</key>
<true/>
```

That's all

**Comment by prouxel-elipssolution** [comment]
Thank you for your answers.

**Comment by pierrickrouxel** [comment]
Thank you for your answers.
