### ISSUE TITLE
There's now a GUI app using this code (SSDP Browser)

### ISSUE THREAD

**Issue by tempelmann** [pierrickrouxel/SSDPClient#19]
I've published an open source [SSDP Browser](https://github.com/tempelmann/SSDP-Browser/releases/tag/v1.0) based on this code, and including the improvements from my pull request #18.

**Comment by pierrickrouxel** [comment]
Nice job. I will add it to the Readme.

**Comment by pierrickrouxel** [comment]
@tempelmann 
I quickly looked your app. Why did you not use swift package manager to include dependencies ?

**Comment by tempelmann** [comment]
I didn't use the Swift Package manager because (a) you had not included my pull request yet and (b) I really don't understand how to use it, especially in newly created projects. I would if I could :)

**Comment by tempelmann** [comment]
But if you can tell me how to do it, I'm gladly learning, or just push a fix on the app, and I'll see what's changed.
My problem was so far that all the instructions, where they say "just add xyz to your package file" assume that I already have one. But I start my projects usually in Xcode, as ObjC projects, and there's no such setup for package management, and I find nothing on the web that explains how to add that.
