### ISSUE TITLE
Error: Bad File Descriptor

### ISSUE THREAD

**Issue by talhazafar914** [pierrickrouxel/SSDPClient#20]
When this function is called readResponses() it gives me an error

Error code: -9982(0x-26FE), Bad file descriptor
  - domain : "com.ibm.oss.Socket.ErrorDomain"
  - errorCode : -9982
  ▿ errorReason : Optional<String>
    - some : "Bad file descriptor"
  - bufferSizeNeeded : 0

    private func readResponses() {
        do {
            var data = Data()
            let (bytesRead, address) = try self.socket!.readDatagram(into: &data)

            if bytesRead > 0 {
                let response = String(data: data, encoding: .utf8)
                let (remoteHost, _) = Socket.hostnameAndPort(from: address!)!
                Log.debug("Received: \(response!) from \(remoteHost)")
                self.delegate?.ssdpDiscovery(self, didDiscoverService: SSDPService(host: remoteHost, response: response!))
            }

        } catch let error {
            Log.error("Socket error: \(error)")
            self.forceStop()
            self.delegate?.ssdpDiscovery(self, didFinishWithError: error)
        }
    }

**Comment by Ilyeesz** [comment]
Did you find a solution? I have the same issue when readResponses() is called!

**Comment by talhazafar914** [comment]
@Ilyeesz  Basically, the app crashes if you haven't granted local network authorization access. So, try calling this function in the following manner. With this code, your app won't crash, but the error will still persist. You will start seeing the available devices on your network. If you still don't see the available devices on the network, you may not have submitted the form for multicast network entitlement.

            let authorization = LocalNetworkAuthorization()
            authorization.requestAuthorization { granted in
                if granted {
                    print("Permission Granted")
                    let discovery = ServiceDiscovery(delegate: self)
                    discovery.start()
                } else {
                    print("Permission denied.")
                }
            }

**Comment by Ilyeesz** [comment]
@talhazafar914 Thank you so much! I'm stil new to programming so bear with me please!
I'm only using the Xcode Simulator to test, and since it does not require multicast network entitlement, I'm still seeing the same error, and there is no devices, and i already tried other SSDP sample projects, which they work just fine, and can see other devices on my netwok. Do you think the issue is still with the entitlement? or maybe i'm doing something wrong in the implementation.

**Comment by pierrickrouxel** [comment]
This is a common mistake. I leave this issue open till I write a quick documentation about this problem in the readme.

**Comment by pierrickrouxel** [comment]
I added a troubleshooting guide in the README.

**Comment by JoeFerrucci** [comment]
You need a special multicast entitlement `com.apple.developer.networking.multicast`
Its a special entitlement and Apple has a review request form, which you can find on their docs page:
https://developer.apple.com/documentation/bundleresources/entitlements/com.apple.developer.networking.multicast
