### ISSUE TITLE
Incorrect parsing

### ISSUE THREAD

**Issue by nmalevich** [pierrickrouxel/SSDPClient#21]
Response:
"HTTP/1.1 200 OK\r\nCache-Control: max-age=1800\r\nDate: Thu, 06 Jun 2024 11:01:02 GMT\r\nST: upnp:rootdevice\r\nEXT: \r\nSERVER: Platform 1.0 His/1.0 UPnP/1.0 DLNADOC/1.50\r\nUSN: uuid:898e0775-23f2-11ef-8b3d-84ba39bb8fb2::upnp:rootdevice\r\nLocation: http://192.168.1.59:38400/MediaServer/rendererdevicedesc.xml\r\n\r\n"

Parsed location:
"http://192.168.1.59:38400/MediaServer/rendererdevicedes"

Correct location:
"http://192.168.1.59:38400/MediaServer/rendererdevicedesc.xml"

Could you please fix that and submit new release? You can do that by replacing "let matches = HeaderRegex.matches(in: response, range: NSRange(location: 0, length: response.count))" with "let matches = HeaderRegex.matches(in: response, range: NSRange(location: 0, length: response.utf16.count))"

Thank you a lot

**Comment by pierrickrouxel** [comment]
@nmalevich I will fix this problem by the end of month.

**Comment by pierrickrouxel** [comment]
Hello @nmalevich, I investigating your issue. Why you string is in UTF-16? Can you tell me more about the UPNP device you use?

**Comment by pierrickrouxel** [comment]
Sorry I understood. It's a swift behaviour.
It's fixed.
