### ISSUE TITLE
Getting crashed issue

### ISSUE THREAD

**Issue by Spatel91111** [pierrickrouxel/SSDPClient#23]
Getting crashed issue on forceStop method as below

EXC_BREAKPOINT 0x000000018d94a3c8

SSDPDiscovery.forceStop() + 99

/// Force stop discovery closing the socket.
    private func forceStop() {
        if self.isDiscovering {
            self.socket!.close() ->  EXC_BREAKPOINT 0x000000018d94a3c8
        }
        self.socket = nil
    }

**Comment by pierrickrouxel** [comment]
@Spatel91111 forceStop is a private function. I don't understand how you can build your project calling the function.
