### ISSUE TITLE
Discovers only 1 device

### ISSUE THREAD

**Issue by oliversluke** [pierrickrouxel/SSDPClient#3]
Dear @pierrickrouxel !

Thank you for this nice piece of work. 

I am currently testing your code and it looks like it only returns the first device which matches the "searchTarget". Is this how it is designed? 

Any idea how I could improve it to return all devices which match the "searchTarget"?

Oliver

**Comment by oliversluke** [comment]
I did some research on this and found the reason is the following:

For me `isDiscovering` always returns `false` as `self.socket!.isConnected` is always `false`.

If I set the return value of `isDiscovering` fix to true, all my devices are identified.

Any idea why `self.socket!.isConnected` is always `false`?

Oliver

**Comment by oliversluke** [comment]
I created a pull request to fix this #4

**Comment by pierrickrouxel** [comment]
Hi Oliver,

I will review your pull request soon.
Thank you for your fix.

**Comment by pierrickrouxel** [comment]
I merged your pull request. Thanks.
