### ISSUE TITLE
Can't find device with real watchOS device

### ISSUE THREAD

**Issue by anlam87** [pierrickrouxel/SSDPClient#7]
It works fine on Simulator, but not work on a real watchOS device. I tested on watchOS 6.1.2. It shows error: "Error code: -9980(0x-26FC), No route to host"

**Comment by pierrickrouxel** [comment]
I don't have Apple Watch, I can't test that.

**Comment by RolandasRazma** [comment]
you can't scan network on real watch. "watchOS" claim is inaccurate.
